apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-taint-fastcpu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-taint-fastcpu
  template:
    metadata:
      labels:
        app: myapp-taint-fastcpu
    spec:
      containers:
      - image: registry.ocp4.example.com:8443/ubi9/ubi:latest
        imagePullPolicy: Always
        name: myapp-taint-fastcpu
        command: ["/bin/sh","-c"]
        args: ["sleep infinity"]
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
      nodeSelector:
        cpu: fast
      tolerations:
      - key: "type"
        value: "mission-critical"
        operator: "Equal"
        effect: "NoSchedule"
