apiVersion: velero.io/v1
kind: Restore
metadata:
  name: db-backup
  namespace: openshift-adp
spec:
  backupName: db-backup-20240908063737
  restorePVs: true
  namespaceMapping:
    database: database-backup
